apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: metrics-app
  labels:
    app: api
    app.kubernetes.io/part-of: metrics-app
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
